version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend_react
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
    command: "npm start"

  backend:
    build: ./backend
    container_name: backend_node
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app"
    command: npm run start
